/**
 * This is automatically generated by sprout plug-in.
 */
package chatbot.conversation.dao;

import java.util.ArrayList;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.mybatis.spring.SqlSessionTemplate;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Repository;

/**
 * 
 * @since 
 * @author Administrator
 */
@Repository("ChatbotDAO")
public class ChatbotDAO {
	
	private Logger logger = LoggerFactory.getLogger(this.getClass());

	@Autowired
    private SqlSessionTemplate sqlSessionTemplate;
	
	@SuppressWarnings("rawtypes")
	public ArrayList checkWordList(String value){		
		if(logger.isInfoEnabled()){
			logger.info("★★★★★★★★★★★★ In checkWordListDB DAO.....");
		}
		return  (ArrayList) sqlSessionTemplate.selectList("Chatbot.checkWordList" , value);
	}
	
	
	public int insertQuestion(Map<String, String> map) {
        return sqlSessionTemplate.insert("Chatbot.insertQuestion", map);
    }
	
	public String getWeatherCode(Map<String, Object> map){		
		if(logger.isInfoEnabled()){
			logger.info("★★★★★★★★★★★★ In getWeatherCode DAO.....");
		}
		return  (String) sqlSessionTemplate.selectOne("Chatbot.getWeatherCode" , map);
	}
}